name: teste

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
            echo "::group::My title"
            echo "step1: Inside group title"

      - name: Step 2
        run: |
            echo "step2: Inside group title"
            echo "::endgroup::"
