name: teste

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |

            echo "::group::My title"
            echo "Inside group title"
            echo "Inside group title"
            ls -l
            echo "Inside group title"
            echo "Inside group title"
            echo "Inside group title"
            echo "Inside group title"
            echo "Inside group title"
            echo "::endgroup::"
